### ISSUE TITLE
Copy pasting is sometimes incomplete

### ISSUE THREAD

**Issue by Mehgugs** [Silverfeelin/Starbound-WEdit#17]
When copy pasting structures it sometimes fails to paste the whole region;  iteration calculations seem to be cutting off the final pastes. eg (1/20 -> 2/19) eventually meeting somewhere less that the starting total.

**Comment by Silverfeelin** [comment]
Thanks for reporting this.

The issue has been addressed in https://github.com/Silverfeelin/Starbound-WEdit/commit/e31ba88cffe42bd1b6a88284ad3f31a10651d638. Although the visible total iterations will still reduce in certain pastes, it should only be beneficial at this point: preventing needless iterations while still placing all placeholders and/or background blocks.

If pasting still fails from version [v1.2.2.1](https://github.com/Silverfeelin/Starbound-WEdit/releases/tag/v1.2.2.1) onwards, please re-open this issue with more details.

Version 1.2.2.1 fixes this and another issue, and has been released on both GitHub and Steam.
