### ISSUE TITLE
Can't get anything to work.

### ISSUE THREAD

**Issue by firespark81** [Silverfeelin/Starbound-WEdit#19]
As stated above. Can't get anything to work. There is an error in the log. No clue how to fix
https://pastebin.com/30CrAGaM

**Comment by Silverfeelin** [comment]
You're using the version for Starbound 1.2.x on Starbound 1.3. Try the version released for Starbound 1.3!
https://github.com/Silverfeelin/Starbound-WEdit/releases/tag/v1.3.0

**Comment by firespark81** [comment]
Mod updated error is gone but noclip still does not work.

**Comment by Silverfeelin** [comment]
*As shown in the installation page: https://github.com/Silverfeelin/Starbound-WEdit/wiki/Installation

If you find any issues please create a new issue!
