### ISSUE TITLE
Suggestion for the item used for the tools

### ISSUE THREAD

**Issue by smb64** [Silverfeelin/Starbound-WEdit#25]
due to frackin universe using trianglium ore, I suggest possible changing it to using the 'artificial brain' or the 'inferior brain' due to the lack of use by any mod that I know of

**Comment by Silverfeelin** [comment]
It would only be a matter of time before another user shows up telling me
to use different items because of other mods. You're free to replace all
triangliumore with another item name in the items.json yourself; it won't
cause any issues.

**Comment by Silverfeelin** [comment]
If you can give me a specific reason why the currently used item is a bad choice and must be changed, please re-open the issue.
