### ISSUE TITLE
using a different layer to display info/debug screen resize

### ISSUE THREAD

**Issue by smb64** [Silverfeelin/Starbound-WEdit#26]
I understand it may be hard to find a layer to use for displaying the info, but the debug screen is always in the way. if there is a way to change which layer the info is displayed, that'd be great! if not, maybe find a way to shrink the debug screen by removing some of the debug info.

**Comment by Silverfeelin** [comment]
I tried to use a local animator, but those place text / images / lines at a position relative to the user, not the world.

Although converting these two just fine, the entity position is a frame old by the time the stuff is rendered, which causes shaking when moving: https://streamable.com/jkjrs

Removing debug info is not possible (and probably a bad idea anyways),

The only other way I can think of would break the multiplayer-compatibility this mod strives to keep intact.

**Comment by smb64** [comment]
maybe make a separate version for those who just wish to use the mod in single player?

**Comment by smb64** [comment]
also, I doubt people would mind the shaking too much, they aren't really going to move much while actually using the tools

**Comment by Silverfeelin** [comment]
So either remake half of WEdit, or downgrade the visuals? Both don't seem viable to me.
You know you can move the camera with <kbd>Ctrl</kbd>, right?

**Comment by smb64** [comment]
yeah, but that doesn't help with the debug screen getting in the way though. that's the main issue for me

**Comment by Silverfeelin** [comment]
Well I'm sorry, but I'm not going to change the way information is displayed unless it's an improvement over the current system. You might be okay with an outline of a selection that shifts one or more blocks as you move around, but for most people this is going to cause confusion and leaving them wish the change was never made.

I assume your monitor has a low resolution, because for me the debug map only takes up a small portion of my 1080p monitor.

**Comment by Silverfeelin** [comment]
Update: @Mehgugs found a way to **move** the log map, meaning you could move it outside of the screen (but it'd still technically be there). This could be added as an add-on (so you'd install WEdit.pak and NoLogMap.pak).
I'm currently working on actual features for the mod so I'll see when I can get to it.

**Comment by smb64** [comment]
thank you and thank @Mehgugs . I'm sure that if this can be done, it'd be highly appreciated by not only me, but many other wedit users.

**Comment by Silverfeelin** [comment]
The below mod will hide the debug window for you. It's not recommended for modders, as it hides a lot of important information while debugging. I'm probably adding it to future releases as well (side by side).

[NoLogMap.zip](https://github.com/Silverfeelin/Starbound-WEdit/files/1203163/NoLogMap.zip)
