### ISSUE TITLE
Nothing is working, might be an item conflict error?

### ISSUE THREAD

**Issue by meepcrux** [Silverfeelin/Starbound-WEdit#27]
Yes I have dash tech and I did click out of the window.
Is it because I have Frackin Universe installed. I can craft the box but the codex says it's another item. Is there a way to change the item ids or a way to fix it?

**Comment by Silverfeelin** [comment]
I have just tried WEdit with https://github.com/sayterdarkwynd/FrackinUniverse/releases/tag/5.4.244. The mod works fine with the trianglium ore base item. Anything wrong must be on your end or due to another mod conflicting. Check your starbound.log for any errors.

The below clips shows me using WEdit on a new character. Commands typed:
```
/admin
/enabletech dash
/spawnitem techconsole

/debug
```

https://streamable.com/xkjg8

**Comment by meepcrux** [comment]
https://www.dropbox.com/s/gblr0xtoc9oofjg/starbound.log?dl=0
Still nothing, I even uninstalled all the tech mods I have

**Comment by Silverfeelin** [comment]
Your log doesn't show that WEdit has been activated in-game , so it's obvious that it won't do anything.
I.e. `[Info] WEdit Controller: Initialized WEdit in 0.09 seconds`.

You either still have a conflict or haven't equipped the dash tech.

**Comment by meepcrux** [comment]
https://streamable.com/skb17
I have everything that I need, any ideas on the conflicts?

**Comment by meepcrux** [comment]
it may be a bug on my end or something. I have gone through all my mods and reinstalled starbound and when through all of the logical issues and it's still not working. I'll uses this mod later at a different date.

**Comment by Silverfeelin** [comment]
WEdit will log that it has loaded if nothing goes wrong. If anything goes wrong, the error will be logged instead.
I don't know what mods you have. The fact that you have the dash tech equipped and WEdit isn't logging that it has loaded shows us that another mod (or user assets) is overwriting the dash tech.
