### ISSUE TITLE
Cannot Pin Certain Blocks

### ISSUE THREAD

**Issue by thakyZ** [Silverfeelin/Starbound-WEdit#28]
I keep getting an error when pinning certain blocks, and while at it, WEdit scripts all crash, and I am not able to use WEdit until I relaunch.
Here are the errors.
https://pastebin.com/ry4HSTQq

**Comment by Mehgugs** [comment]
This is fixed in the current build of wedit `1.3.2.2` but there has not been a release with these changes yet. 
Thanks for  reporting, I'm going to close this since it's fixed just not released yet.
