### ISSUE TITLE
Wedit allows people to paste objects with uuids when objects with that uuid already exist.

### ISSUE THREAD

**Issue by Mehgugs** [Silverfeelin/Starbound-WEdit#30]

**Comment by Silverfeelin** [comment]
What would be a better solution, generating new UUIDs when an UUID is found, or removing the UUID entirely?

**Comment by Mehgugs** [comment]
A better solution is to not place them; they have "unique IDs" for a reason, Ill make a PR once I've thought of a way to do the filtering

**Comment by Silverfeelin** [comment]
Not necessarily true. Objects can have UUIDs to make them globally identifiable. Objects having an UUID does not mean "there should only be one of me".

**Comment by Silverfeelin** [comment]
This was fixed quite a while ago by assigning new uniqueId's to pasted objects that have an existing uniqueId. Another solution would be to generate a new id only if the existing id can no longer be located. For now we'll keep things like this.
