### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by Grungebob01** [Silverfeelin/Starbound-WEdit#31]
It dosent let me use any of the tools

**Comment by Grungebob01** [comment]
I went into admin mode but it still dosent work

**Comment by Silverfeelin** [comment]
Like Shadox said you also need to have the dash tech equipped. Make sure you use (click) your item outside of your inventory. Simply clicking on a tool inside your inventory or any other container will not work.

You can check your starbound.log to see if WEdit is actually being loaded:
`WEdit Controller: Initialized WEdit.`
