### ISSUE TITLE
Improvement of Paint Tool

### ISSUE THREAD

**Issue by Greymanz** [Silverfeelin/Starbound-WEdit#34]
Currently the paint tool just adds an interface that has the same functionality and usage as the MM Paint tool. The colors are shitty and there's only a few to pick from.

materialHueShift is a property which allows you to set the hueshift to metric fucktons of different variety. The oddity that the paint tool doesnt allow you to set this to ANY variety is a shame.

![image](https://user-images.githubusercontent.com/15857782/47184015-271c8f80-d2ef-11e8-8b25-9efb9bd9b84e.png)

Compare this to the paint tool. 

![image](https://user-images.githubusercontent.com/15857782/47184043-3b608c80-d2ef-11e8-8c3d-7b12bda53290.png)

**Comment by Greymanz** [comment]
I closed it primarily as a caution. There is an assumption that unlike the color variable which is built into the tile texture, every new hue variation would require entirely new sets to be added to the "texture pages" that other programs with this rendering engine often use. It's not to say that this is absolute, however I think that further testing of a massive variety of hue shifts is in order, and then possibly a warning of some matter sent to the user, as a means of telling them to avoid making too many hueshift variants.

Or don't. If custom sleeves have taught me anything, it doesn't matter for most people if something is mildly/moderately game or performance breaking so long as it looks pretty.

**Comment by Silverfeelin** [comment]
I'm actually quite impressed by the engine when it comes to image/rendering calculations. It handles thousands if not hundreds of thousands of replace directives from string literals with next to no impact on game performance (on machines that live in today's age).

I have dyed thousands upon thousands of blocks. No dirt went untouched. My planet now looks as if invaded by hundreds of different inklings. Although this does not qualify as a benchmark, I could not get my game to drop frames any more than usual.

The dye tool will be replaced with a hue selection slider. A preview shows what the selected hue looks like on various blocks.
![image](https://user-images.githubusercontent.com/17196309/47942931-28a3a580-def4-11e8-94e5-d26c7f735cfb.png)

**Comment by Silverfeelin** [comment]
This feature has been implemented on the wip-fsm branch. It will be merged and hopefully released before or around the release of Starbound 1.4.

For now you can download the source code of the branch to try out the feature.

Wiki will be updated when the merge happens.

**Comment by Greymanz** [comment]
Wow! This is seriously amazing, thanks. No doubt this will be a much better tool for building than the basic color tool we have now.
