### ISSUE TITLE
noclip is buggy

### ISSUE THREAD

**Issue by dogranger45** [Silverfeelin/Starbound-WEdit#38]
basically, i had to rebind noclip since it wouldnt work, and it still didnt work
then, when i beamed down to the planet, i was stuck in it
i couldnt get out after pressing my noclip key and beaming up, and going to menu and switching back to my character didnt work

**Comment by Silverfeelin** [comment]
In the WEdit settings, what is your noclip bind?
See: https://github.com/Silverfeelin/Starbound-WEdit/wiki/Settings-Interface

**Comment by dogranger45** [comment]
> In the WEdit settings, what is your noclip bind?
> See: https://github.com/Silverfeelin/Starbound-WEdit/wiki/Settings-Interface

my keybind was changed from g to v, and i made sure the bind in controls was also the same
i switched to v since im used to it on gmod

**Comment by Silverfeelin** [comment]
In the WEdit settings, please change your mind to `specialTwo` (write that out). That'll allow you to use <kbd>v</kbd> to toggle noclip (after reloading your character from the main menu).

A game limitation stops us from simply binding to any key, so WEdit maps the option `specialTwo` to the control you bound to v. This option `specialTwo` was formerly named `g`, hence the confusion.
