### ISSUE TITLE
Stamp: Logging materials used.

### ISSUE THREAD

**Issue by Silverfeelin** [Silverfeelin/Starbound-WEdit#4]
[Requested by /u/DixonButtz.](https://www.reddit.com/r/starbound/comments/4x1skv/i_heard_you_guys_like_copying_and_pasting_ruins/d6ep34p)

The amount of materials required for copies visible in the starbound log.

#### Requires:
* Keeping track of material counts when populating the copy table.
* Formatted log output for a variable list of materials.

#### Current workaround:
None.

**Comment by SupaCURE** [comment]
Yeah, just encountered this problem as well. Seems to cause consistent crashing whenever the game tries to write to the log. Sad to say I can't even log in to my server at this point. A bit to ambitious with a large base haha

**Comment by Silverfeelin** [comment]
Sorry? This is a feature request. Could you check your starbound.log and share the error you're getting?

**Comment by Silverfeelin** [comment]
Added in commit [3c5e46963605d7760180ad615592fecdc87c6a1a](https://github.com/Silverfeelin/Starbound-WEdit/commit/3c5e46963605d7760180ad615592fecdc87c6a1a).

The materials, matmods, objects and liquids are written to the starbound.log file whenever a copy is made with the Stamp or the Schematic Maker.
