### ISSUE TITLE
None of the Items are Working

### ISSUE THREAD

**Issue by ExotixFantonix** [Silverfeelin/Starbound-WEdit#40]
Hi! I just found your mod today, and I have the Dash equipped, and I have no other mods installed beside the ones you told me to install and WEdit. I've tried every item; Even the NoClip doesn't work. Plz help me.

Here's a link to the mods I have installed
![Mods Installed](https://user-images.githubusercontent.com/47545183/57199512-b9177d00-6f4d-11e9-9965-a06eb1529ad4.png)

**Comment by ExotixFantonix** [comment]
Also, when you have the Dash equipped, it's supposed to shoot you in the direction you press, and it doesn't do that anymore either

**Comment by ExotixFantonix** [comment]
Nevermind, I think it was my version
Didn't check it first, I'm an idiot lol

**Comment by Silverfeelin** [comment]
Wrong game version or mod version? I'd recommend subscribing to the Steam version of the mods if you have the game on Steam. It'll auto download the latest version of all mods.
