### ISSUE TITLE
incompatible with Aurora's SB 1.4 Mod

### ISSUE THREAD

**Issue by Vortetty** [Silverfeelin/Starbound-WEdit#46]
The wedit keybind always resets to the "special 2" keybind from Aurora's SB 1.4 Mod when the game loads. is it possible you you to look into this, or suggest a way to fix this? i have tested multiple keys, it seems to happen regardless of the key that is set.

Edit: i just figured this out, the problem seems to be hailing from this: 
```
{
    "op" : "add",
    "path" : "/keyActions/player/-",
    "value" : { "label" : "Special 2", "action" : "PlayerTechAction2" }
  },
```

both mods use PlayerTechAction2, i will see if i can figure out how to make a patch, if i do i will post it here.

**Comment by Silverfeelin** [comment]
No need. Keep that key bound to <kbd>g</kbd> (for both, as they are the same). Simply change the WEdit bind in the WEdit settings instead of the game controls.

Change the `Noclip Bind` option to something like `up down` to make <kbd>w</kbd> + <kbd>s</kbd> toggle noclip.

**Comment by Vortetty** [comment]
i actually do have the keybind set to g in worldedit settings, however the keybind it uses is the one in the keybind settings menu

**Comment by Vortetty** [comment]
the problem is that i want the keybind for special 2 to be "o" and the noclip keybind to be "g". however when i set it like this, "o" toggles noclip and prevents me from using o+shift or o+w, etc. here is how i have it set: 
![wedit config](https://github.com/Vortetty/js-hosting-/raw/master/WEDIT%20BROKEN%20ONE.PNG)
![keybind config](https://github.com/Vortetty/js-hosting-/raw/master/WEDIT%20BROKEN%20TWO.PNG)

but if i press o, i end up flying and it prevents me from using the key combos i want.

**Comment by Silverfeelin** [comment]
There's only 3 special keys (first one being the normal tech action F). I assume your special 3 key also does something, so you'll have to compromise somewhere. WEdit Toggle Noclip is the same as special 2, so whichever you set last will be the key for special 2.

The difference between Aurora's mod and WEdit is that WEdit allows you to bind to basically any input option **supported by tech scripts**. This includes movement keys, shift, left or right mouse button and the three action keys. So basically, if you set the Noclip bind to `specialTwo specialThree` it will Toggle noclip whenever you hit what's bound to those two options.

 Here's all options supported by WEdit for the Noclip bind: https://github.com/Silverfeelin/Starbound-Keybinds/wiki/Options

**Comment by Vortetty** [comment]
i have set the keybinds the same in the settings menu, and the custom menu to specialTwo specialThree, however as said before, whatever was set in the wedit menu is ignored, is it possible to add a new action to add to this mod to avoid incompatabilities?

**Comment by Vortetty** [comment]
> i have set the keybinds the same in the settings menu, and the custom menu to specialTwo specialThree, however as said before, whatever was set in the wedit menu is ignored, is it possible to add a new action to add to this mod to avoid incompatabilities?

i seem to have just needed to warp somewhere for this to take effect, case closed, this works.
