### ISSUE TITLE
DISREGARD. The stamp tool was working when I first downloaded this mod, but now doesn't add or destroy blocks when pasting.

### ISSUE THREAD

**Issue by triskadia** [Silverfeelin/Starbound-WEdit#53]
Hi, I'm not sure if this mod is still being supported, but I was wondering if there is a way to fix this problem I'm having with the stamp tool. 
I downloaded the mod recently for a byos ship build, I was able to copy and paste large chunks of my ship, but then I came across a smaller section that was giving me trouble and I couldn't get the parameters just right and ended up spam clicking the undo while pasting that section. 
Some time passes and I'm no longer able to paste a given copied selection. It will output in the debug ui that it is processing blocks, liquids, etc, with an appropriate(?)(number changes with size of paste, but not sure if there is something wrong here) number but then just not place any blocks nor lag as it usually had before.
At first I thought it was because I was including a ship hatch, an object, whereas I'd been copying only blocks previously, but I have a feeling it was broken from when I was pressing undo. I've since tried beaming up and down, uninstalled and reinstalled the mod off of the workshop. 
(I have tried replacing my ship, player and metadata files with a backup made earlier in the day, but I do not recall if those backups were made before or after pressing undo and wrecking the stamp tool, as I went about other parts of the build that didn't require it for a good chunk of time before coming around)

Edit: the schematic pasting function also seems to be broken in the same way.

Edit: Thank you for the wonderful mod. I am an idiot.

**Comment by Silverfeelin** [comment]
I did move on from Starbound but let me guess, you were trying to paste in the air without any adjacent blocks? That's a limitation of the Starbound API which is why the paste has to work with slow iterations in the first place 🫠

I had some hopes the devs were going to improve the API but they moved on from the game before I did.
