### ISSUE TITLE
Suggestion : Bigger Matmod and Block Pinner size.

### ISSUE THREAD

**Issue by DrShadox** [Silverfeelin/Starbound-WEdit#7]
Hello , so like the title say its a suggestion about matmod and block pinner , at the moment it work like a pencil (1x1) , but it should be usefull to have additional option like a 2x2 and 3x3 or things like that (or have 1x1 + 2x2 + 3x3 when taking a sample ?).

Thx if you can consider that , this is the link of the suggestion on the WEdit discussion page (but it say the same thing like here) : http://community.playstarbound.com/threads/wedit.116953/page-3#post-3000693

have a nice day and sorry for my english.

**Comment by Silverfeelin** [comment]
Currently working on this feature. In the interface, you'd be able to configure:
* Brush shapes.
 * Currently limited to `square` or `circle`.
 * The shape affects the pencil, pinned blocks and pinned matmods.
* Individual sizes or radii for the tools mentioned above.

![](http://i.los.so/e/starbound_2016-08-23_02-10-59.png)

As this feature request requires me to rework the tools (they were initially never set up to support multiple blocks), there's some testing left to do before I commit the changes.

**Comment by DrShadox** [comment]
Awesome work , if i can help for test in game ask me ^^

Also in an another game we had something like that , and while using the wellmousse (+hold a key , for ex alt or shift) we was able to enlarge/reduce the radius , it can be a solution if never you have knowledge for that.

Anyway good luck , and thx so much for work on my request , 1 mod for rules them all \o/


(sry for my english)

**Comment by Silverfeelin** [comment]
I'm afraid changing the radius won't quite be that easy. There's not a lot of input methods available, so I'm planning to put it in the WEdit interface for the matter manipulator upgrade panel.
I'll be changing the way changes are applied so that it doesn't require a /reload.

**Comment by Silverfeelin** [comment]
Added in commit [2bf4b95a1b8225eabb13d725b138cc694f368349](https://github.com/Silverfeelin/Starbound-WEdit/commit/2bf4b95a1b8225eabb13d725b138cc694f368349) and [7070eeb4cff962bfe531d3ef578966ef438ab89f](https://github.com/Silverfeelin/Starbound-WEdit/commit/7070eeb4cff962bfe531d3ef578966ef438ab89f).

Settings can be adjusted through the matter manipulator upgrade panel (which requires [Manipulated UI](https://github.com/Silverfeelin/Starbound-ManipulatedUI)).

Note that these commits are currently in the [experimental branch](https://github.com/Silverfeelin/Starbound-WEdit/tree/experimental) only. There's no release with these changes as of right now.
